Add instances of  `MessagePack` for basic types
TokTok/hs-msgpack-binary pull request #7
Opened 2016-10-05 21:10 UTC by Martoon-00

2016-10-05 23:09 UTC, iphydf requested changes

2016-10-05 23:09 UTC, iphydf commented on src/Data/MessagePack/Instances.hs
> +import           Data.MessagePack.Generic
Add `()` at the end, since we're only importing instances, no other symbols.

2016-10-06 10:04 UTC, iphydf commented on src/Data/MessagePack/Instances.hs
> +import           Data.MessagePack.Generic
This comment was on line 5, meaning the `Generic` import. But you're right, `MessagePack` also doesn't need functions. Write this:

``` haskell
import           Data.MessagePack.Class   (MessagePack)
import           Data.MessagePack.Generic ()
```

2016-10-06 10:04 UTC, iphydf commented
After that's done, please squash your commits into one.

2016-10-07 10:28 UTC, Martoon-00 commented on src/Data/MessagePack/Instances.hs
> +import           Data.MessagePack.Generic
Oh, really. Thank you

2016-10-07 17:25 UTC, iphydf commented on src/Data/MessagePack/Instances.hs
> +import           Data.MessagePack.Class   (MessagePack ())
I don't think the () is necessary here. Did you try without it?

2016-10-10 19:00 UTC, iphydf commented
Thanks, I don't get notified if there is a change. Perhaps explicitly reply to the review thread when you fix something next time :).

2016-10-10 19:01 UTC, iphydf approved these changes

2016-10-10 19:01 UTC, merged

2016-10-11 05:52 UTC, Martoon-00 commented
Got it, thanks for your patience!